name: Do stuff on check-file changes

on: push
# pull_request:
#   branches: [master]
#   types: [closed]

jobs:
  generate-previous-file:
    runs-on: ubuntu-latest
    # if: |
    #   github.event.action == 'closed' &&
    #   github.event.pull_request.merged == true
    steps:
      # - name: Get old file
      #   run: git cat-file -p HEAD^:./check-file.json > previous-check-file.json
      # - run: |
      #     mkdir diff
      #     cd diff
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: "14"
      # - run: npm install
      - name: Find diff between files
        uses: actions/github-script@v6
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result)
